name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.1
    - name: Creating env-config.json
      run: |
        cd /home/runner/work/SMAT/SMAT/nimrod/tests/
        contents="$(jq '.java_home = "/opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64" | .maven_home = "/opt/hostedtoolcache/maven/3.5.4/x64"' env-config.json)"
        echo "${contents}" > env-config.json
        cd /home/runner/work/SMAT/SMAT
    - name: Test with pytest
      run: |
        pytest -k 'not test_general_behavior_study_semantic_conflict'