name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: checar
      run: 
        cd Testes
    - name: Test
      run: |
        python main.py